### ISSUE TITLE
Suggestion: Support for PAL/GC Majora's Mask

### ISSUE THREAD

**Issue by marcrobledo** [MarocZan/Better-Majora-s-Mask#2]
I finally got some time to test this, it's amazing! Thanks for your work.

Would be possible to add support for Europe ROM? Specially the GameCube revision, which runs at 60hz.
It would be great to see all the Redux enhancements working in european languages.

**Comment by ShadowOne333** [comment]
Adding the uncensored assets and other fixes from other versions of Majora's Mask should be easily doable, as it's all documented here and in a way easily explained so the changes done to MM US v1.0 can be done to the PAL version too:
https://github.com/ShadowOne333/Zelda64-Redux-Documentation

However, the problem comes when porting all of the Randomizer features into PAL.
The MM Randomizer project focuses on Majora's Mask v1.0 (U), and since most of the features rely on code hooks to work properly (and some other RAM changes), porting the features to PAL would be quite a task to achieve.

I don't think it would happen anytime soon, but...
If playing Redux in another language is what you desire, the Patcher64 Tool software allows for implementing other languages into a Zelda 64 Redux project:
https://github.com/Admentus64/Patcher64Plus-Tool

You can pretty much compile a MM Redux ROM with another language like Polish or Russian. I know OoT has a lot, not sure how many there are for MM, but at least there's that as an option.

PS: Hi Marc! Nice to see you here too :P

**Comment by marcrobledo** [comment]
Hey @ShadowOne333 :-D

I don't mind about the Randomizer features. I'd be fine with just the Redux additions.
Unfortunately, MM has no spanish language in the Patcher64Plus-Tool.


EDIT: Wait, I just saw the patcher was updated on 10th March with spanish support, going to try it out now!

**Comment by marcrobledo** [comment]
It works like a charm!
It uses the USA ROM, but since my beloved savegame extracted from my old original cartridge seems to be compatible, I cannot complain :-)

Thank you all for your work.

**Comment by ShadowOne333** [comment]
Awesome! Glad to know you managed to get Redux with Spanish working properly :D
Iirc all the other European languages should now be included as well for MM with Patcher64, so you can choose whichever language you prefer with Redux now. :)

Enjoy it! (And sorry for the late response :P )
